# Etapa 1: Construcción (Builder)
FROM maven:3.9-eclipse-temurin-17-alpine AS builder
WORKDIR /app
# Copiar primero el pom para aprovechar el caché de capas de Docker
COPY pom.xml .
RUN mvn dependency:go-offline -B
# Copiar código fuente y compilar
COPY src ./src
RUN mvn clean package -DskipTests

# Crear un JRE personalizado mínimo con jlink para reducir el tamaño del contenedor
RUN $JAVA_HOME/bin/jlink \
    --add-modules java.base,java.compiler,java.desktop,java.instrument,java.management,java.naming,java.prefs,java.rmi,java.scripting,java.security.jgss,java.sql,java.sql.rowset,java.xml,jdk.crypto.ec,jdk.unsupported \
    --strip-debug \
    --no-man-pages \
    --no-header-files \
    --compress=2 \
    --output /javaruntime

# Etapa 2: Ejecución (Runtime)
FROM alpine:3.20
WORKDIR /app

ARG DOCKER_USER=ubuntu
ARG DOCKER_UID=1000

RUN adduser -D -u $DOCKER_UID $DOCKER_USER

ENV JAVA_HOME=/opt/java/openjdk
ENV PATH="${JAVA_HOME}/bin:${PATH}"
COPY --from=builder /javaruntime $JAVA_HOME

COPY --from=builder /app/target/{{service}}-backend-*.jar app.jar

RUN chown -R $DOCKER_USER:$DOCKER_USER /app

EXPOSE 8080

ENV TZ="America/La_Paz"

USER $DOCKER_USER

ENTRYPOINT ["java", "-jar", "app.jar"]
